format = """
$git_branch\
$git_state\
$git_status\
$directory\
$cmd_duration\
"""

add_newline = false

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = "[$all_status$ahead_behind]($style) "

[directory]
format = "[$path]($style) "

[cmd_duration]
format = "underwent [$duration]($style) "
